' Developer Express Code Central Example:
' How to bind a property inside the BarStaticItem.ContentTemplate to a ViewModel property
' 
' Assign the ViewModel instance to the RibbonControl.DataContext property. While
' binding a property in the BarStaticItem.ContentTemplate, use the RibbonControl
' name as the ElementName. The binding path should be the same as when you address
' the RibbonControl properties.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2567

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace My


	<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property
	End Class
End Namespace
