// Developer Express Code Central Example:
// How to bind a property inside the BarStaticItem.ContentTemplate to a ViewModel property
// 
// Assign the ViewModel instance to the RibbonControl.DataContext property. While
// binding a property in the BarStaticItem.ContentTemplate, use the RibbonControl
// name as the ElementName. The binding path should be the same as when you address
// the RibbonControl properties.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E2567

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonControl_Ex.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
